version: "3"

networks:
  network:
    ipam:
      driver: default
      config:
        - subnet: '177.7.0.0/16'

services:
  # web:
  #   build:
  #     context: ./web
  #     dockerfile: ./Dockerfile
  #   container_name: online-web
  #   restart: always
  #   ports:
  #     - '443:443'
  #   command: [ 'nginx-debug', '-g', 'daemon off;' ]
  #   networks:
  #     network:
  #       ipv4_address: 177.7.0.11

  # server:
  #   build:
  #     context: ./server
  #     dockerfile: ./Dockerfile
  #   container_name: online-server
  #   restart: always
  #   ports:
  #     - '127.0.0.1:8888:8888'
  #   depends_on:
  #     - mysql
  #     - redis
  #   links:
  #     - mysql
  #     - redis
  #   networks:
  #     network:
  #       ipv4_address: 177.7.0.12

  mysql:
    image: mysql:8.0.21
    container_name: online-mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci #设置utf8字符集
    restart: always
    volumes:
      - $PWD/data/mysql/data:/var/lib/mysql
    ports:
      - 3306:3306  # host物理直接映射端口为13306
    environment:
      MYSQL_DATABASE: 'online' # 初始化启动时要创建的数据库的名称
      MYSQL_ROOT_PASSWORD: 'xsC4sdf43aX' # root管理员用户密码
    networks:
      network:
        ipv4_address: 177.7.0.13

  redis:
    image: redis:6.0.6
    container_name: online-redis # 容器名
    restart: always
    command: redis-server --requirepass xsC4sdf43aX
    ports:
      - '6379:6379'
    volumes:
      - $PWD/data/redis:/data
    networks:
      network:
        ipv4_address: 177.7.0.14
  mongodb:
    image: mongo:latest
    restart: always
    container_name: online-mongodb
    volumes:
      - $PWD/data/mongo/db:/data/db
      - $PWD/data/mongo/log:/var/log/mongodb
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: online
      MONGO_INITDB_ROOT_PASSWORD: 43invVDwfsd4
      MONGO_INITDB_DATABASE: online
    networks:
      network:
        ipv4_address: 177.7.0.15
  rabbitmq:
    image: rabbitmq:3.8-management
    container_name: online_rabbitmq
    restart: always
    hostname: rabbitmq_host
    ports:
      - 15672:15672   # web UI 管理接口
      - 5672:5672       # 生产者和消费者连接使用的接口
    volumes:
      - $PWD/data/rabbitmq/log:/var/log/rabbitmq #挂载 RabbitMQ日志
      - $PWD/data/rabbitmq/data:/var/lib/rabbitmq #挂载 RabbitMQ数据
    environment:
      - RABBITMQ_DEFAULT_USER=hotpot  # 用户名
      - RABBITMQ_DEFAULT_PASS=sCviEv334Vds # 密码 
    networks:
      network:
        ipv4_address: 177.7.0.16
  flower:
    image: mher/flower:latest
    container_name: online_flower
    restart: always
    command: celery flower
    ports:
      - '5555:5555'
    environment:
      CELERY_BROKER_URL: pyamqp://hotpot:sCviEv334Vds@177.7.0.16:5672/
      CELERY_RESULT_BACKEND: mongodb://online:43invVDwfsd4@177.7.0.15:27017/online?authSource=admin
    networks:
      network:
        ipv4_address: 177.7.0.17
        